-- 中文：V1.6 原始 Agent 示例任务表；SaaS 的用户任务使用下方 ai_task 表。
-- English: Original V1.6 demo task table; SaaS user jobs are stored in ai_task below.
CREATE TABLE IF NOT EXISTS agent_task (
    id BIGSERIAL PRIMARY KEY,
    task_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 中文：SaaS 核心表。PostgreSQL 是持久化事实来源，Redis 只缓存进度和处理中间数据。
-- English: Core SaaS tables. PostgreSQL is the durable source of truth; Redis only holds progress and processing data.
-- plan 是套餐限制；user_account 是账号；plan 先建好以满足用户的外键约束。
-- plan stores limits, user_account stores identities, and plan is created first for the user's foreign key.
CREATE TABLE IF NOT EXISTS plan (
    plan_code VARCHAR(32) PRIMARY KEY,
    plan_name VARCHAR(64) NOT NULL,
    monthly_tasks INTEGER NOT NULL CHECK (monthly_tasks >= 0),
    max_file_size BIGINT NOT NULL CHECK (max_file_size > 0),
    max_tool_calls INTEGER NOT NULL CHECK (max_tool_calls > 0),
    tool_timeout_ms BIGINT NOT NULL CHECK (tool_timeout_ms > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    plan_code VARCHAR(32) NOT NULL DEFAULT 'FREE' REFERENCES plan(plan_code),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(1000) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    content_type VARCHAR(255),
    file_role VARCHAR(32) NOT NULL DEFAULT 'INPUT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- 中文/English：按用户和时间查询文件列表时使用的复合索引 / Speeds up owner-scoped recent-file lookups.
CREATE INDEX IF NOT EXISTS idx_user_file_owner ON user_file(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    input_file_id BIGINT NOT NULL REFERENCES user_file(id),
    prompt TEXT NOT NULL,
    workflow_type VARCHAR(32) NOT NULL DEFAULT 'FREEFORM',
    workflow_options TEXT NOT NULL DEFAULT '{}',
    result_summary TEXT,
    status VARCHAR(32) NOT NULL,
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    result_file_id BIGINT REFERENCES user_file(id),
    error_message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);
-- 中文/English：按用户查看最近任务时的索引 / Index for a user's recent task history.
CREATE INDEX IF NOT EXISTS idx_ai_task_owner_created ON ai_task(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_task_input (
    task_id BIGINT NOT NULL REFERENCES ai_task(id) ON DELETE CASCADE,
    file_id BIGINT NOT NULL REFERENCES user_file(id),
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    PRIMARY KEY (task_id, file_id),
    UNIQUE (task_id, ordinal)
);

INSERT INTO ai_task_input(task_id,file_id,ordinal)
SELECT id,input_file_id,0 FROM ai_task
WHERE input_file_id IS NOT NULL ON CONFLICT DO NOTHING;

-- 中文：每次已接受的任务记一笔额度消耗；task_id 唯一约束防止同任务重复计费。
-- English: Records accepted task usage; the unique task_id prevents charging the same task twice.
CREATE TABLE IF NOT EXISTS usage_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    usage_type VARCHAR(32) NOT NULL,
    usage_month CHAR(7) NOT NULL,
    task_id BIGINT UNIQUE REFERENCES ai_task(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_usage_owner_month ON usage_record(user_id, usage_month);

-- 中文：套餐可调用工具白名单；Java 在每次工具调用时查询该表授权。
-- English: Plan-to-tool allowlist; Java checks this table for each tool call.
CREATE TABLE IF NOT EXISTS plan_tool_permission (
    plan_code VARCHAR(32) NOT NULL REFERENCES plan(plan_code),
    tool_name VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (plan_code, tool_name)
);

-- 中文/English：幂等初始化套餐示例值 / Idempotently seed the initial development plans.
INSERT INTO plan(plan_code, plan_name, monthly_tasks, max_file_size, max_tool_calls, tool_timeout_ms)
VALUES
    ('FREE', '免费版', 20, 10485760, 8, 8000),
    ('BASIC', '基础版', 300, 52428800, 15, 15000),
    ('PRO', '专业版', 2000, 209715200, 30, 30000)
ON CONFLICT (plan_code) DO NOTHING;

INSERT INTO plan_tool_permission(plan_code, tool_name, enabled)
SELECT p.plan_code, t.tool_name, TRUE
FROM plan p
CROSS JOIN (VALUES ('read_excel'), ('filter'), ('sort'), ('top'), ('export_excel')) AS t(tool_name)
ON CONFLICT (plan_code, tool_name) DO NOTHING;
